name: arenaai_pyenv
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=openblas
  - brotli-python=1.0.9=py311h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - certifi=2025.4.26=py311hca03da5_0
  - cffi=1.17.1=py311h3eb5a62_1
  - greenlet=3.1.1=py311h313beb8_0
  - httpx=0.28.1=py311hca03da5_0
  - httpx-sse=0.4.0=py311hca03da5_0
  - jsonpatch=1.33=py311hca03da5_1
  - langchain=0.3.25=py311hca03da5_0
  - langchain-community=0.3.24=pymin39_hff2d567_0
  - langchain-text-splitters=0.3.8=py311hca03da5_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.29=hea593b9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - mypy_extensions=1.0.0=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - numpy-base=1.26.4=py311hfbfe69c_0
  - openssl=3.0.16=h02f6b3c_0
  - packaging=24.2=py311hca03da5_0
  - pip=25.1=pyhc872135_2
  - propcache=0.3.1=py311h80987f9_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.11=hb885b13_0
  - python-dotenv=1.1.0=py311hca03da5_0
  - pyyaml=6.0.2=py311h80987f9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.32.3=py311hca03da5_1
  - requests-toolbelt=1.0.0=py311hca03da5_0
  - setuptools=78.1.1=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - typing_extensions=4.12.2=py311hca03da5_0
  - typing_inspect=0.9.0=py311hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.2.13=h18a0788_1
  - zstandard=0.23.0=py311h1a4646a_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - fastapi==0.115.12
      - frozenlist==1.6.0
      - h11==0.16.0
      - httpcore==1.0.9
      - idna==3.10
      - jiter==0.10.0
      - jsonpointer==3.0.0
      - langchain-core==0.3.60
      - langchain-openai==0.3.18
      - langgraph==0.4.7
      - langgraph-checkpoint==2.0.26
      - langgraph-prebuilt==0.2.1
      - langgraph-sdk==0.1.70
      - langsmith==0.3.42
      - marshmallow==3.26.1
      - multidict==6.4.4
      - mypy-extensions==1.1.0
      - numpy==2.2.6
      - openai==1.81.0
      - orjson==3.10.18
      - ormsgpack==1.10.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - regex==2024.11.6
      - sniffio==1.3.1
      - sqlalchemy==2.0.41
      - starlette==0.46.2
      - tenacity==9.1.2
      - tiktoken==0.9.0
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - xxhash==3.5.0
      - yarl==1.20.0
prefix: /opt/anaconda3/envs/arenaai_pyenv
